# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 */8 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - name: General
        uses: ion232/metrics@master
        with:
          filename: images/general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ion232
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, followup, languages, habits
          config_timezone: Europe/London
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts_type: graph
          plugin_habits_facts: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used

      - name: Achievements
        uses: ion232/metrics@master
        with:
          filename: images/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ion232
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_only:  >-
            member, maintainer, inspirer, polyglot, developer, stargazer, sponsor, scripter, packager, explorer